### ISSUE TITLE
NamedManagerに右クリックメニューのDOMを生成する役割

### ISSUE THREAD

**Issue by Narazaka** [Ikagaka/NamedManager.js#13]
NamedManagerにコンテキストメニューのDOM生成を要求できるようにすべき。
コンテキストメニューは伺かの既存実装上画面上に単一であるUI要素であり、アプリケーションに1つであるNamedManagerから生成すべき。

名前等はなんでもいいが
・NamedManager#open_context_menu(menuitem_hierarchy)
メニュー名とコールバックを持つメニュー階層を示すリストmenuitem_hierarchyをとる。
すでにメニューがある場合はそれを閉じてから新規に生成する。
・NamedManager#close_context_menu()
すでにメニューがある場合はそれを閉じる。

が望ましい気がする。

またできれば何も無いところをクリックした場合にメニューを閉じる挙動もあると良い。
メニューは再利用性のため別クラスで実装すべき。

**Comment by legokichi** [comment]
コンテキストメニューは右クリをトリガーとして表示されるので
必要なAPIは状況に応じて階層メニューを定義するためコールバック。
```
NamedManager#contextmenu((event:{scopeId:number})=> menuitem_hierarchy): void
```
なAPIを追加しました

**Comment by legokichi** [comment]
内部的にはjQueryプラギンをそのまま使っているが
そのうち分解統合してMenuクラスになる予定
